apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
        - name: docker-image-pull-secret
      containers:
      - name: app
        image: jfabian1205/backend:latest
        ports:
        -  containerPort: 3005
        envFrom:
        - secretRef:
            name: app-secret

