name: CI

on:
  push:
    branches: [ main ]

jobs:
  test-and-validate:
    runs-on: ubuntu-latest
    env:                               
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
      PORT: ${{ secrets.PORT }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm i

      - name: Lints
        run: |
          npm run prepare
          npm run check-all


      - name: Tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: docker build
        run: docker build -t backend:${{github.sha}} .

      - name: docker login
        run: docker login --username ${{secrets.DOCKER_LOGIN}} --password ${{secrets.DOCKER_PASSWORD}}

      - name: tag docker image
        run: docker tag backend:${{github.sha}} ${{secrets.DOCKER_LOGIN}}/backend:${{github.sha}}

      - name: push docker image
        run: docker push ${{secrets.DOCKER_LOGIN}}/backend:${{github.sha}}
